### ISSUE TITLE
Pagination of Two Separate Elements

### ISSUE THREAD

**Issue by jmusicc** [st3ph/jquery.easyPaginate#1]
I know this is old and probably the only version you made but I think this is a great plugin.
The only problem is that you can't paginate two different elements on a single page.

ex. I paginate two different tables and both button sets control the same (last) table that I paginated.

If you ever have the time to implement pagination of multiple elements that would be awesome.

**Comment by st3ph** [comment]
Even using 2 different selectors ?
I didn't work on this plugin since a long long time =)

**Comment by ssjogus** [comment]
hi, 

any answer to this? this is really useful plugin, but it is not working if there are two paginations come on same page.. 

any idea how to do this?

any help will be appreciated.
