### ISSUE TITLE
Instead of selector

### ISSUE THREAD

**Issue by bindashsandeep** [st3ph/jquery.easyPaginate#3]
Hi Friend,

If I will use class instead of any element like img, tbody?

I want to use a class. Can this will be paginated?

My code is like:

> div id="tobepaginate"
div class="item col-xs-12">one  /div
div class="item col-xs-12">two /div
div class="item col-xs-12">three  /div
div class="item col-xs-12">four  /div
div class="item col-xs-12">five   /div
/div>

**Comment by st3ph** [comment]
It works with anything

**Comment by bindashsandeep** [comment]
Thanks for your reply 👍 Actually I am new to javascript, that's why I'm confused. Can you please suggest me how to write Stéphane :)

$(function() {
	$('#products').easyPaginate({
		paginateElement: 'img',
		elementsPerPage: 6,
		effect: 'climb'
	});
});

what to put on 'paginateElement' and what to write for 'img'
